config/routes.rb
Rails.application.routes.draw do
  resources :form_answers
  resources :custom_form_inputs
  resources :custom_forms
  resources :forms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/custom_form.rb
class CustomForm < ApplicationRecord
  has_many :custom_form_inputs

  validates :title, presence: true

  accepts_nested_attributes_for :custom_form_inputs
end

app/models/custom_form_input.rb
class CustomFormInput < ApplicationRecord
  belongs_to :custom_form

  validates :label, :kind,   presence: true

  enum kind: {
    text: 0,
    number: 1,
    date: 2,
    select_field: 3
  }
end

app/models/form_answer.rb
class FormAnswer < ApplicationRecord
  belongs_to :custom_form_input
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  protect_from_forgery with: :null_session
end

app/controllers/custom_form_inputs_controller.rb
class CustomFormInputsController < ApplicationController
end

app/controllers/custom_forms_controller.rb
class CustomFormsController < ApplicationController
  before_action :set_custom_form, only: %i[ show edit update destroy ]

  # GET /custom_forms or /custom_forms.json
  def index
    @custom_forms = CustomForm.all
  end

  # GET /custom_forms/1 or /custom_forms/1.json
  def show
    render json: {
      title: @custom_form.title,
      inputs: CustomFormInput.where(custom_form: @custom_form)
    }
  end

  # GET /custom_forms/new
  def new
    @custom_form = CustomForm.new
  end

  # GET /custom_forms/1/edit
  def edit
  end

  # POST /custom_forms or /custom_forms.json
  def create
    custom_form = CustomForm.create!(title: params[:title])

    params[:custom_form_inputs].map do |input|
      CustomFormInput.create!(custom_form: custom_form, label: input[:label], kind: input[:kind], required: input[:required], max_length: input[:max_length], placeholder: input[:placeholder])
    end


    render json: custom_form, status: :created
  end

  # PATCH/PUT /custom_forms/1 or /custom_forms/1.json
  def update
    @custom_form.update!(title: params[:title]) if params[:title].present?

    params[:custom_form_inputs].map do |input|
      CustomFormInput.find(input[:id]).update!(label: input[:label], kind: input[:kind], required: input[:required], max_length: input[:max_length], placeholder: input[:placeholder])
    end

    render json: {
      title: @custom_form.title,
      inputs: CustomFormInput.where(custom_form: @custom_form)
    }
  end

  # DELETE /custom_forms/1 or /custom_forms/1.json
  def destroy
    @custom_form.destroy!

    respond_to do |format|
      format.html { redirect_to custom_forms_path, status: :see_other, notice: "Custom form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_form
      @custom_form = CustomForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def custom_form_params
      params.fetch(:custom_form, {
        title: params[:title]
      })
    end
end

app/controllers/form_answers_controller.rb
class FormAnswersController < ApplicationController
  def create
    params[:form_answers].map do |answer|
      FormAnswer.create!(custom_form_input: CustomFormInput.find(answer[:custom_form_input_id]), value: answer[:value])
    end

    render json: {
      message: "Form answers were successfully submitted."
    }, status: :created
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custom_form_inputs_helper.rb
module CustomFormInputsHelper
end

app/helpers/custom_forms_helper.rb
module CustomFormsHelper
end

app/helpers/form_answers_helper.rb
module FormAnswersHelper
end

app/views/custom_forms/_custom_form.html.erb
<div id="<%= dom_id custom_form %>">
</div>

app/views/custom_forms/_form.html.erb
<%= form_with(model: custom_form) do |form| %>
  <% if custom_form.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(custom_form.errors.count, "error") %> prohibited this custom_form from being saved:</h2>

      <ul>
        <% custom_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/custom_forms/edit.html.erb
<% content_for :title, "Editing custom form" %>

<h1>Editing custom form</h1>

<%= render "form", custom_form: @custom_form %>

<br>

<div>
  <%= link_to "Show this custom form", @custom_form %> |
  <%= link_to "Back to custom forms", custom_forms_path %>
</div>

app/views/custom_forms/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Custom forms" %>

<h1>Custom forms</h1>

<div id="custom_forms">
  <% @custom_forms.each do |custom_form| %>
    <%= render custom_form %>
    <p>
      <%= link_to "Show this custom form", custom_form %>
    </p>
  <% end %>
</div>

<%= link_to "New custom form", new_custom_form_path %>

app/views/custom_forms/new.html.erb
<% content_for :title, "New custom form" %>

<h1>New custom form</h1>

<%= render "form", custom_form: @custom_form %>

<br>

<div>
  <%= link_to "Back to custom forms", custom_forms_path %>
</div>

app/views/custom_forms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @custom_form %>

<div>
  <%= link_to "Edit this custom form", edit_custom_form_path(@custom_form) %> |
  <%= link_to "Back to custom forms", custom_forms_path %>

  <%= button_to "Destroy this custom form", @custom_form, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Atelier" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>